apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scania-app
  annotations:
    github.com/project-slug: alejovicu/scania-app
spec:
  type: service
  owner: user:alejovicu
  lifecycle: experimental
  providesApis:
    - http://localhost:8080