name: Release scania-app image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'version'
env:
  REGISTRY: docker.io
  IMAGE_NAME: alejovicu/scania-app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
      docker build -t ${{ env.IMAGE_NAME }}:$(cat version) .
      echo ${{ secrets.DOCKER_HUB_PASS }} | docker login --username ${{ env.DOCKER_HUB_USER }} --password-stdin ${{ env.REGISTRY }}
      docker push ${{ env.IMAGE_NAME }}:$(cat version)